2
CAJO_OPEN count.txt 0 0
CAJO_OPEN abs.txt 1 1
CAJO_READ 0
CAJO_JUMP_IF_ZERO_TO 12
CAJO_JUMP_IF_POSITIVE_TO 10
CAJO_JUMP_IF_NEGATIVE_TO 7
CAJO_PRINT
CAJO_COPY_TO_MEMORY 0
CAJO_SUBTRACT 0
CAJO_SUBTRACT 0
CAJO_WRITE 1
CAJO_JUMP 2
CAJO_CLOSE 0
CAJO_CLOSE 1