1
CAJO_SET_MEMORY 10 2
CAJO_SET_MEMORY 1 1
CAJO_SET_MEMORY 0 0
CAJO_COPY_FROM_MEMORY 0
CAJO_PRINT
CAJO_ADD 1
CAJO_COPY_TO_MEMORY 0
CAJO_SUBTRACT 2
CAJO_JUMP_IF_ZERO_TO 12
CAJO_JUMP 3
CAJO_SET_MEMORY 0 0
CAJO_COPY_FROM_MEMORY 0
CAJO_PRINT